const ALLOWED_VARIABLES: Record<string, string[]> = {
  CLIENT_NODE: [
    'id',
    'requests',
    'label',
    'type',
    'valet',
    'flavor',
    'providerStyle',
    'provider',
    'technologyOfClient',
    'technologyOfServer',
  ],
  SERVER_NODE: [
    'id',
    'acceptedEndpoints',
    'endpoints',
    'label',
    'type',
    'tcpConnectionsToPostgres',
    'tcpConnections',
    'capacity',
    'prefetchLimit',
    'registeredTopics',
    'flavor',
    'providerStyle',
    'provider',
    'technologyOfServer',
  ],
  LOADBALANCER_NODE: [
    'id',
    'label',
    'type',
    'strategy',
    'routes',
    'flavor',
    'providerStyle',
    'provider',
    'technologyOfLoadBalancer',
  ],
  GATEWAY_NODE: [
    'id',
    'label',
    'type',
    'strategy',
    'routes',
    'routeRules',
    'serviceMapping',
    'typeOfApiGateway',
    'flavor',
    'providerStyle',
    'provider',
  ],
  REDIS_NODE: [
    'id',
    'label',
    'type',
    'data',
    'technologyOfRedis',
    'flavor',
    'providerStyle',
    'provider',
  ],
  POSTGRES_NODE: [
    'id',
    'label',
    'type',
    'table',
    'dbName',
    'data',
    'technologyOfPostgres',
    'flavor',
    'providerStyle',
    'provider',
  ],
  MESSAGE_QUEUE_NODE: [
    'id',
    'label',
    'type',
    'processingType',
    'queueSize',
    'queueSizeLimit',
    'overflowBehavior',
    'overflowBehavious',
    'flavor',
    'providerStyle',
    'provider',
  ],
  PUBSUB_NODE: [
    'id',
    'label',
    'type',
    'topic',
    'subscribers',
    'activeSubscribers',
    'registeredTopics',
    'technologyOfPubSub',
    'flavor',
    'providerStyle',
    'provider',
  ],
};

const ALLOWED_VARIABLES_MAP: Record<string, string[]> = {
  ...ALLOWED_VARIABLES,
  client: ALLOWED_VARIABLES.CLIENT_NODE,
  server: ALLOWED_VARIABLES.SERVER_NODE,
  loadbalancer: ALLOWED_VARIABLES.LOADBALANCER_NODE,
  gateway: ALLOWED_VARIABLES.GATEWAY_NODE,
  redis: ALLOWED_VARIABLES.REDIS_NODE,
  postgres: ALLOWED_VARIABLES.POSTGRES_NODE,
  messagequeue: ALLOWED_VARIABLES.MESSAGE_QUEUE_NODE,
  pubsub: ALLOWED_VARIABLES.PUBSUB_NODE,
};

export default ALLOWED_VARIABLES_MAP;
