name: CI / Automated Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Run Unit Tests & Build Verification
    runs-on: ubuntu-latest

    steps:
    # it will clone the repo in ubuntu latest
      - name: Checkout Code
        uses: actions/checkout@v4

      # it will setup nodejs version 20 and cache the npm packages
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

    # it will install the dependencies
      - name: Install Dependencies
        run: npm ci

      # it will run the vitest unit tests
      - name: Run Vitest Unit Tests
        run: npm test

      # It will verify the next.js build
      - name: Verify Next.js Build
        run: npm run build
